### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ueen** [puiooo/startpage_enhancer#2]
show favicons and add maps link like this https://addons.mozilla.org/de/firefox/addon/duckduckgo-maps/

**Comment by mriooo** [comment]
Nice idea, will consider! :)

**Comment by mriooo** [comment]
I just added the two things, hope you like it!

**Comment by ueen** [comment]
Awesome will try 😍

**Comment by ueen** [comment]
Hey, looks great, if i could suggest something further, maybe there could be setting to have either OSM or Google Maps?
And it would be awesome if the icons could be on the lefthand side of the url (where the anonym browse feauture is right know), so maybe they could just be switched, so the anonym browse would be on the right and the icon on the left. That way i feel its easier to see the icon if you're reading the title and url from left to right - but its already awsome, thanks very much for integrating these feautures, happy new year!

**Comment by ueen** [comment]
oh also i took a look at the code and using googles api to get the favicons kinda defeats the purpose of startpage :D mayb it should be optional then with a disclaimer or is there another api thats a bit more privacy cautious (like where is duckduckgo getting their favicons)?

**Comment by ueen** [comment]
i found https://icon.horse/ maybe thats an alternative?

**Comment by ueen** [comment]
adressed it here https://github.com/puiooo/startpage_enhancer/pull/4
would love if you could update it :)

**Comment by mriooo** [comment]
Thanks for your help! I've uploaded the new version to the store, might take some hours to take effect!

**Comment by ueen** [comment]
Awesome thanks :)
