### ISSUE TITLE
Maps Buttons

### ISSUE THREAD

**Issue by ueen** [puiooo/startpage_enhancer#5]
maps buttons look like actual buttons
also somtimes the addon doesnt seem to lead (no buttons, no favicons)
anyone else noticed this?

**Comment by mriooo** [comment]
Yup, they seem to have changed a lot of stuff :) I am having the same problems

**Comment by mriooo** [comment]
Fixed it, will bump version in store soon :)

It seems they cleaned their code up, same css now for all pages :grin:

**Comment by ueen** [comment]
Hey, works great again, just the maps button style is kind of faded, is this supposed to be like this?
<img width="916" alt="Bildschirmfoto 2022-06-25 um 10 23 22" src="https://user-images.githubusercontent.com/5067479/175765182-55372669-8f60-4f98-a194-dc8527545574.png">

Making the font a bit more darker maybe 70% or somth would be great IMOH :)

**Comment by ueen** [comment]
works great, just sometimes the maps button are kind of greyed out (not sure when, only happen sometimes), can you verify?

<img width="916" alt="Bildschirmfoto 2022-06-25 um 10 23 22" src="https://user-images.githubusercontent.com/5067479/175766076-97355458-d968-4128-b88f-ce3ca09a79ff.png">

**Comment by mriooo** [comment]
Ah, looks like i Am using darkmode and you are not :-) 
Didnt even know startpage had different themes. I am on vacation the next 2 weeks, feel free to Look i to it if you're motivated :-D
Otherwise i'll Look i to it after my vac. 

Best 
Puiooo
-- 
 Gesendet mit Tutanota, der sicheren & werbefreien Mailbox. 



25. Juni 2022, 10:54 von ***@***.***:

**Comment by ueen** [comment]
Enjoy your holidays! I'm busy with exams myself, i'll try to keep an eye on it, it mostly works, only sometimes its greyed out, really wierd.

**Comment by mriooo** [comment]
good luck with your exams! 
Will look into it when I got time
