### ISSUE TITLE
Sometimes the maps button are greyed out

### ISSUE THREAD

**Issue by mriooo** [puiooo/startpage_enhancer#6]
When in Light Mode, the Maps Buttons sometimes are greyed out.

> 
> works great, just sometimes the maps button are kind of greyed out (not sure when, only happen sometimes), can you verify?
> 
> <img width="916" alt="Bildschirmfoto 2022-06-25 um 10 23 22" src="https://user-images.githubusercontent.com/5067479/175766076-97355458-d968-4128-b88f-ce3ca09a79ff.png">
> 
> _Originally posted by @ueen in https://github.com/puiooo/startpage_enhancer/issues/5#issuecomment-1166232225_

**Comment by ueen** [comment]
should also be fixed in https://github.com/puiooo/startpage_enhancer/pull/9
