### ISSUE TITLE
Maps buttons cover UI

### ISSUE THREAD

**Issue by dktharrop** [puiooo/startpage_enhancer#7]
![image](https://github.com/puiooo/startpage_enhancer/assets/42393999/3cc345d5-ab00-4f9e-aaea-a1377b2f997b)

The buttons for opening maps cover the search filter UI. Is there any way to turn the buttons off?

**Comment by mriooo** [comment]
Thanks for the heads up, i'll Take a Look 👍

**Comment by mriooo** [comment]
Todo: overwrite css-1j2749q and add two more columns

`.css-1j2749q {
  display: grid;
  grid-template-columns: 0.5fr 0.5fr 0.5fr 0.5fr;
}`

**Comment by ueen** [comment]
fixed it here https://github.com/puiooo/startpage_enhancer/pull/9 :)

i redid the implementation as to make it more simple and robust to future changes

and i remove the class making trouble `.css-1j2749q` entierly as i cant really see it doing anything essential and it doesnt seem too smart to hardcode such a class name as it may change
